name = "redux"
description = "A fork of the Apollo theme for Zola with a few liberties"
min_version = "0.0.5"
license = "MIT"
homepage = "https://github.com/seniormars/redux"
# demo = "https://seniormars.com/redux"

# Of course, credit to not-matthias


# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

[author]
name = "seniormars"
homepage = "https://github.com/seniormars"
